---
kind: pipeline
type: docker
name: default

steps:
- name: RDP
  image: ubuntu:20.04
  commands:
  - apt update
  - apt upgrade -y
  - useradd rock6064
  - printf "dragon\ndragon\n" | passwd rock6064
  - usermod -aG root rock6064
  - apt install --no-install-recommends --no-install-suggests unzip wget xrdp ubuntu-desktop -y
  - wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  - unzip ngrok-stable-linux-amd64.zip
  - ./ngrok authtoken 1c4LXcUXOpIOAKT3obuC8qCHzOE_2wWv9tDhXnrCgxGfj5DLp
  - /etc/init.d/xrdp restart
  - sleep 5
  - ./ngrok tcp 3389
  environment:
    DEBIAN_FRONTEND: noninteractive
